# prefer pip
name: whisper_py311
channels:
  - nvidia/label/cuda-11.8.0
  - nvidia
  - huggingface
  - conda-forge
  - defaults
dependencies:
  - python~=3.11
  - pip>=23.2.1
  - wheel
  - build
  - flit
  - cudatoolkit~=11.8.0
  - cudnn~=8.9.0
  - jaxlib=*=*cuda*
  - jax
  - cuda-nvcc
  - nccl
  - orjson
  - dill
  - pathos
  - joblib
  - accelerate>=0.20.3
  - transformers>=4.27.4
  - cached-property
  - virtualenv
