# use this only when you know what you are doing
# prefer pip
name: whisper_py310
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - flax
  - transformers>=4.27.4
  - ffmpeg
  - cached-property
  - accelerate>=0.20.3
  - build
  - flit
  - joblib
  - pathos
  - dill
  - virtualenv
  - jupyter
  - ipython
  - ipykernel
  - ipywidgets
  - notebook
  - nbconvert
  - tqdm
  - ipywidgets
  - nodejs
  - widgetsnbextension
  - black
  - mypy
