# prefer pip
name: whisper_py311
channels:
  - nvidia/label/cuda-11.8.0
  - nvidia
  - conda-forge
  - huggingface
  - nodefaults
dependencies:
  - python~=3.11
  - appdirs
  - conda-lock
  - pip>=23.2.1
  - wheel
  - python-build
  - flit
  - virtualenv
  # cuda
  - cuda-toolkit~=11.8.0
  - cudnn~=8.8.0
  - cuda-nvcc
  - nccl
  - mkl
  # profilers
  - filprofiler
  - yappi
  - viztracer
  # dl
  - transformers
  # utils
  - ffmpeg
  # libs
  - structlog
  - uvicorn
