# prefer pip
name: whisper_py311
channels:
  - nvidia/label/cuda-11.8.0
  - nvidia
  - huggingface
  - conda-forge
  - nodefaults
dependencies:
  - python~=3.11
  - pip>=23.2.1
  - wheel
  - python-build
  - flit
  - virtualenv
  # cuda
  - cudatoolkit~=11.8.0
  - cudnn~=8.9.0
  - jaxlib=*=*cuda*
  - jax
  - cuda-nvcc
  - nccl
  - mkl
  # dl
  - transformers
  # utils
  - ffmpeg
  # libs
  - structlog
